# Cooked with love by netchef

cert_path = "./combined-cacert.pem"

[networks]

[networks.alfonso-0]
sequencers = [
"dev-infra-alfonso-0-opn-geth-f-sequencer-0",
"dev-infra-alfonso-0-opn-geth-f-sequencer-1",
"dev-infra-alfonso-0-opn-reth-f-sequencer-2",
]

[sequencers]

[sequencers.dev-infra-alfonso-0-opn-geth-f-sequencer-0]
raft_addr = "alfonso-0-opn-geth-f-sequencer-0-op-conductor-raft.primary.infra.dev.oplabs.cloud:50050"
conductor_rpc_url = "https://alfonso-0-opn-geth-f-sequencer-0-op-conductor.primary.infra.dev.oplabs.cloud"
node_rpc_url = "https://alfonso-0-opn-geth-f-sequencer-0-op-node.primary.infra.dev.oplabs.cloud"
voting = true

[sequencers.dev-infra-alfonso-0-opn-geth-f-sequencer-1]
raft_addr = "alfonso-0-opn-geth-f-sequencer-1-op-conductor-raft.primary.infra.dev.oplabs.cloud:50050"
conductor_rpc_url = "https://alfonso-0-opn-geth-f-sequencer-1-op-conductor.primary.infra.dev.oplabs.cloud"
node_rpc_url = "https://alfonso-0-opn-geth-f-sequencer-1-op-node.primary.infra.dev.oplabs.cloud"
voting = true

[sequencers.dev-infra-alfonso-0-opn-reth-f-sequencer-2]
raft_addr = "alfonso-0-opn-reth-f-sequencer-2-op-conductor-raft.primary.infra.dev.oplabs.cloud:50050"
conductor_rpc_url = "https://alfonso-0-opn-reth-f-sequencer-2-op-conductor.primary.infra.dev.oplabs.cloud"
node_rpc_url = "https://alfonso-0-opn-reth-f-sequencer-2-op-node.primary.infra.dev.oplabs.cloud"
voting = true

