# Cooked with love by netchef

cert_path = "./combined-cacert.pem"

[networks]

[networks.jovian-alpha]
sequencers = [
"dev-infra-jovian-alpha-opn-geth-f-sequencer-0",
"dev-infra-jovian-alpha-opn-geth-f-sequencer-1",
"dev-infra-jovian-alpha-opn-reth-f-sequencer-2",
]

[sequencers]

[sequencers.dev-infra-jovian-alpha-opn-geth-f-sequencer-0]
raft_addr = "jovian-alpha-opn-geth-f-sequencer-0-raft.primary.infra.dev.oplabs.cloud:50050"
conductor_rpc_url = "https://jovian-alpha-opn-geth-f-sequencer-0-con.primary.infra.dev.oplabs.cloud"
node_rpc_url = "https://jovian-alpha-opn-geth-f-sequencer-0-op-node.primary.infra.dev.oplabs.cloud"
voting = true

[sequencers.dev-infra-jovian-alpha-opn-geth-f-sequencer-1]
raft_addr = "jovian-alpha-opn-geth-f-sequencer-1-raft.primary.infra.dev.oplabs.cloud:50050"
conductor_rpc_url = "https://jovian-alpha-opn-geth-f-sequencer-1-con.primary.infra.dev.oplabs.cloud"
node_rpc_url = "https://jovian-alpha-opn-geth-f-sequencer-1-op-node.primary.infra.dev.oplabs.cloud"
voting = true

[sequencers.dev-infra-jovian-alpha-opn-reth-f-sequencer-2]
raft_addr = "jovian-alpha-opn-reth-f-sequencer-2-raft.primary.infra.dev.oplabs.cloud:50050"
conductor_rpc_url = "https://jovian-alpha-opn-reth-f-sequencer-2-con.primary.infra.dev.oplabs.cloud"
node_rpc_url = "https://jovian-alpha-opn-reth-f-sequencer-2-op-node.primary.infra.dev.oplabs.cloud"
voting = true

