chains:
    - nodes:
          - kind: "node"
            name: "sequencer-0"
            spec:
                kind: "sequencer"
                lightNode: true
                el:
                    kind: "op-geth"
                    spec:
                        kind: "full"
                cl:
                    kind: "op-node"
                    deps:
                        services:
                            - "proxyd-cl"

          - kind: "node"
            name: "sequencer-1"
            spec:
                kind: "sequencer"
                lightNode: true
                el:
                    kind: "op-reth"
                    spec:
                        kind: "full"
                cl:
                    kind: "op-node"
                    deps:
                        services:
                            - "proxyd-cl"

          - kind: "node"
            name: "sequencer-2"
            spec:
                kind: "sequencer"
                lightNode: true
                el:
                    kind: "op-reth"
                    spec:
                        kind: "full"
                cl:
                    kind: "op-node"
                    deps:
                        services:
                            - "proxyd-cl"

          - kind: "node"
            name: "rpc-0"
            spec:
                kind: "rpc"
                lightNode: true
                el:
                    kind: "op-reth"
                    spec:
                        kind: "archive"
                cl:
                    kind: "op-node"
                    deps:
                        services:
                            - "proxyd-cl"

          - kind: "node"
            name: "rpc-1"
            spec:
                kind: "rpc"
                lightNode: true
                el:
                    kind: "op-reth"
                    spec:
                        kind: "archive"
                cl:
                    kind: "op-node"
                    deps:
                        services:
                            - "proxyd-cl"

          - kind: "node"
            name: "snapsync-0"
            spec:
                kind: "snapsync"
                lightNode: true
                el:
                    kind: "op-geth"
                    spec:
                        kind: "full"
                cl:
                    kind: "op-node"
                    deps:
                        services:
                            - "proxyd-cl"

          - kind: "node"
            name: "snapsync-1"
            spec:
                kind: "snapsync"
                lightNode: true
                el:
                    kind: "op-reth"
                    spec:
                        kind: "full"
                cl:
                    kind: "op-node"
                    deps:
                        services:
                            - "proxyd-cl"

          - kind: "node"
            name: "sn-0"
            spec:
                kind: "supernode-el"
                el:
                    kind: "op-reth"
                    spec:
                        kind: "full"

          - kind: "node"
            name: "sn-1"
            spec:
                kind: "supernode-el"
                el:
                    kind: "op-reth"
                    spec:
                        kind: "archive"

          - kind: "node"
            name: "sn-2"
            spec:
                kind: "supernode-el"
                el:
                    kind: "op-reth"
                    spec:
                        kind: "archive"

          - kind: "node"
            name: "sn-3"
            spec:
                kind: "supernode-el"
                el:
                    kind: "op-reth"
                    spec:
                        kind: "archive"
      services:
          - kind: "batcher"
            name: "op-batcher"
            spec:
                kind: "op-batcher"
            deps:
                nodes:
                    - "sequencer-0"
                    - "sequencer-1"
                    - "sequencer-2"

          - kind: "public-rpc"
            name: "proxyd-public"
            spec:
                kind: "proxyd"
            deps:
                nodes:
                    - "rpc-0"
                    - "rpc-1"
                services:
                    - "op-interop-filter"

          - kind: "proposer"
            name: "op-proposer"
            spec:
                kind: "op-proposer"
            deps:
                nodes:
                    - "rpc-0"

          - kind: "op-dispute-mon"
            name: "op-dispute-mon"
            spec:
                kind: "op-dispute-mon"
            deps:
                nodes:
                    - "rpc-0"

          - kind: "peer-mgmt-service"
            name: "peer-mgmt-service"
            spec:
                kind: "peer-mgmt-service"
            deps:
                nodes:
                    - "sequencer-0"
                    - "sequencer-1"
                    - "sequencer-2"
                    - "rpc-0"
                    - "rpc-1"
                    - "snapsync-0"
                    - "snapsync-1"

          - kind: "op-conductor-mon"
            name: "op-conductor-mon"
            spec:
                kind: "op-conductor-mon"
            deps:
                nodes:
                    - "sequencer-0"
                    - "sequencer-1"
                    - "sequencer-2"

          - kind: "op-conductor-ops"
            name: "op-conductor-ops"
            spec:
                kind: "op-conductor-ops"
            deps:
                nodes:
                    - "sequencer-0"
                    - "sequencer-1"
                    - "sequencer-2"

          - kind: "proxyd"
            name: "proxyd-cl"
            spec:
                kind: "proxyd"
                values:
                    consensusLayerMode: true
            deps:
                services:
                    - "op-supernode-0"
                    - "op-supernode-1"
                    - "op-supernode-2"

    - nodes:
          - kind: "node"
            name: "sequencer-0"
            spec:
                kind: "sequencer"
                lightNode: true
                el:
                    kind: "op-geth"
                    spec:
                        kind: "full"
                cl:
                    kind: "op-node"
                    deps:
                        services:
                            - "proxyd-cl"

          - kind: "node"
            name: "sequencer-1"
            spec:
                kind: "sequencer"
                lightNode: true
                el:
                    kind: "op-reth"
                    spec:
                        kind: "full"
                cl:
                    kind: "op-node"
                    deps:
                        services:
                            - "proxyd-cl"

          - kind: "node"
            name: "sequencer-2"
            spec:
                kind: "sequencer"
                lightNode: true
                el:
                    kind: "op-reth"
                    spec:
                        kind: "full"
                cl:
                    kind: "op-node"
                    deps:
                        services:
                            - "proxyd-cl"

          - kind: "node"
            name: "rpc-0"
            spec:
                kind: "rpc"
                lightNode: true
                el:
                    kind: "op-reth"
                    spec:
                        kind: "archive"
                cl:
                    kind: "op-node"
                    deps:
                        services:
                            - "proxyd-cl"

          - kind: "node"
            name: "rpc-1"
            spec:
                kind: "rpc"
                lightNode: true
                el:
                    kind: "op-reth"
                    spec:
                        kind: "archive"
                cl:
                    kind: "op-node"
                    deps:
                        services:
                            - "proxyd-cl"

          - kind: "node"
            name: "snapsync-0"
            spec:
                kind: "snapsync"
                lightNode: true
                el:
                    kind: "op-geth"
                    spec:
                        kind: "full"
                cl:
                    kind: "op-node"
                    deps:
                        services:
                            - "proxyd-cl"

          - kind: "node"
            name: "snapsync-1"
            spec:
                kind: "snapsync"
                lightNode: true
                el:
                    kind: "op-reth"
                    spec:
                        kind: "full"
                cl:
                    kind: "op-node"
                    deps:
                        services:
                            - "proxyd-cl"

          - kind: "node"
            name: "sn-0"
            spec:
                kind: "supernode-el"
                el:
                    kind: "op-reth"
                    spec:
                        kind: "full"

          - kind: "node"
            name: "sn-1"
            spec:
                kind: "supernode-el"
                el:
                    kind: "op-reth"
                    spec:
                        kind: "archive"

          - kind: "node"
            name: "sn-2"
            spec:
                kind: "supernode-el"
                el:
                    kind: "op-reth"
                    spec:
                        kind: "archive"

          - kind: "node"
            name: "sn-3"
            spec:
                kind: "supernode-el"
                el:
                    kind: "op-reth"
                    spec:
                        kind: "archive"
          - kind: "node"
            name: "sn-4"
            spec:
                kind: "supernode-el"
                el:
                    kind: "op-reth"
                    spec:
                        kind: "archive"
          - kind: "node"
            name: "sn-4"
            spec:
                kind: "supernode-el"
                el:
                    kind: "op-reth"
                    spec:
                        kind: "archive"
      services:
          - kind: "batcher"
            name: "op-batcher"
            spec:
                kind: "op-batcher"
            deps:
                nodes:
                    - "sequencer-0"
                    - "sequencer-1"
                    - "sequencer-2"

          - kind: "public-rpc"
            name: "proxyd-public"
            spec:
                kind: "proxyd"
            deps:
                nodes:
                    - "rpc-0"
                    - "rpc-1"
                services:
                    - "op-interop-filter"

          - kind: "peer-mgmt-service"
            name: "peer-mgmt-service"
            spec:
                kind: "peer-mgmt-service"
            deps:
                nodes:
                    - "sequencer-0"
                    - "sequencer-1"
                    - "sequencer-2"
                    - "rpc-0"
                    - "rpc-1"
                    - "snapsync-0"
                    - "snapsync-1"

          - kind: "op-conductor-mon"
            name: "op-conductor-mon"
            spec:
                kind: "op-conductor-mon"
            deps:
                nodes:
                    - "sequencer-0"
                    - "sequencer-1"
                    - "sequencer-2"

          - kind: "op-conductor-ops"
            name: "op-conductor-ops"
            spec:
                kind: "op-conductor-ops"
            deps:
                nodes:
                    - "sequencer-0"
                    - "sequencer-1"
                    - "sequencer-2"

          - kind: "challenger"
            name: "op-challenger"
            spec:
                kind: "op-challenger"
            deps:
                nodes:
                    - "rpc-0"

          - kind: "proxyd"
            name: "proxyd-cl"
            spec:
                kind: "proxyd"
                values:
                    consensusLayerMode: true
            deps:
                services:
                    - "op-supernode-0"
                    - "op-supernode-1"
                    - "op-supernode-2"

services:
    - kind: "supernode"
      name: "op-supernode-0"
      spec:
          kind: "op-supernode"
      deps:
          nodes:
              - "sn-0"

    - kind: "supernode"
      name: "op-supernode-1"
      spec:
          kind: "op-supernode"
      deps:
          nodes:
              - "sn-1"

    - kind: "supernode"
      name: "op-supernode-2"
      spec:
          kind: "op-supernode"
      deps:
          nodes:
              - "sn-2"

    - kind: "supernode"
      name: "op-supernode-3"
      spec:
          kind: "op-supernode"
          values:
            env:
              OP_SUPERNODE_VN_420120070_SYNCMODE: "consensus-layer"
              OP_SUPERNODE_VN_420120071_SYNCMODE: "consensus-layer"
              OP_SUPERNODE_VN_ALL_SYNCMODE: "consensus-layer"
      deps:
          nodes:
              - "sn-3"


    - kind: "supernode"
      name: "op-supernode-4"
      spec:
          kind: "op-supernode"
          values:
            image: 
              tag: "v0.2.1"
            env:
              OP_SUPERNODE_VN_420120070_SYNCMODE: "consensus-layer"
              OP_SUPERNODE_VN_420120071_SYNCMODE: "consensus-layer"
              OP_SUPERNODE_VN_ALL_SYNCMODE: "consensus-layer"
      deps:
          nodes:
              - "sn-4"


    - kind: "interop-filter"
      name: "op-interop-filter"
      spec:
          kind: "op-interop-filter"
      deps:
          nodes:
              - "rpc-0"
