name: Devnet Request
description: Request a new devnet.
title: "[Devnet Request]: "
labels: ["scoping"]

body:
  - type: input
    id: name
    attributes:
      label: Name
      description: What should we call this devnet?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What features are going to be deployed in this devnet?
    validations:
      required: true
  - type: textarea
    id: acceptance_tests
    attributes:
      label: Acceptance Tests
      description: What acceptance tests need to be run to validate this devnet?
      placeholder: |
        - Focus on new features (general network tests are covered by Platforms)
        - Which tests will be executed manually? Which do you plan to automate?
        - Any special test scenarios we should be aware of and plan for?
        - Feel free to link to another doc if this is defined there
    validations:
      required: true
  - type: textarea
    id: security_documents
    attributes:
      label: Design Docs, Specs, and FMAs
      description: Please provide links to applicable design documents, specifications, and FMAs, which are required for devnet deployment
      placeholder: |
        - Links to design documents
        - Links to specs
        - Links to FMAs
        - Especially call out any changes to network topology, as these involve changes to Platforms tooling
    validations:
      required: true
  - type: textarea
    id: configurations
    attributes:
      label: Configurations
      description: What configurations are needed for this devnet?
      placeholder: |
        - specific component versions or configurations
        - any differences from a typical network topology (e.g., introduces new components, change in # or types of components)
        - anything else we need to know to deploy this devnet?
